# SwiftLint Configuration for Chameleon
reporter: "xcode"

# Paths to include for linting
included:
  - Chameleon
  - ChameleonTests
  - ChameleonUITests

# Paths to exclude from linting
excluded:
  - Chameleon.xcodeproj
  - .build
  - .git
  - .github
  - Packages
  - DerivedData
  - .swiftpm
  - Chameleon/Assets.xcassets

# Opt-in rules (rules not enabled by default)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - joined_default_parameter
  - literal_expression_end_indentation
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20

# Naming conventions
type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - db
    - os
    - x
    - y
    - z

# Rules to ignore for test files
force_unwrapping:
  excluded:
    - ChameleonTests
    - ChameleonUITests

large_tuple:
  excluded:
    - ChameleonTests
    - ChameleonUITests

for_where:
  excluded:
    - ChameleonTests
    - ChameleonUITests

